name: 'PROS Depot'
description:
  'Generates a PROS depot JSON file from GitHub releases for PROS template
  distribution'
author: 'Jerry Lum'

branding:
  icon: 'box'
  color: 'black'

inputs:
  github_token:
    description:
      'GitHub token for accessing repository releases (optional, defaults to the
      token of the user running the action)'
    required: false
  include_prereleases:
    description:
      'Include prereleases in the depot (all, stable-only, prerelease-only)'
    required: false
    default: 'all'
  push:
    description:
      'Push the generated depot JSON file to the target branch (optional,
      defaults to true)'
    required: false
    default: 'true'
  target_repo:
    description:
      'Target repository to push the depot JSON file to (optional, defaults to
      the repository running the action)'
    required: false
    default: ''
  target_branch:
    description:
      'Branch to store the generated depot JSON file (optional, defaults to
      depot)'
    required: false
    default: 'depot'
  target_path:
    description: 'Path where the JSON file will be stored in the target branch'
    required: false
    default: 'stable.json'

outputs:
  depot:
    description: 'The content of the depot JSON file'

runs:
  using: node20
  main: dist/index.js
